    DROP TABLE IF EXISTS BATTERY;  
    CREATE TABLE BATTERY (  
    CODE INT(11) AUTO_INCREMENT PRIMARY KEY,  
    NAME VARCHAR(50) NOT NULL,  
    POSTALCODE INT(8) NOT NULL, 
    WATT INT(5) NOT NULL 
    );  